# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java 
name: '$(Rev:r)'

parameters:
- name: businessGroup
  displayName: Select a Business Group
  type: string
  default: 'APIs'
  values:
  - 'APIs'
  - 'B2B'

- name: environment
  displayName: Select an Environment
  type: string
  default: 'ALL'
  values:
  - 'ALL'
  - 'DEV'
  - 'QA'
  - 'STAGE'
  - 'PROD'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: APIMANAGER 
  displayName: API MANAGER CONFIG
  jobs:
  - job: BuildApiManager
    displayName: Build API Manager

    steps:
    - script: echo "Building the project for ${{ parameters.environment }}"
      displayName: 'Run a one-line script'
    - script: |
        echo "Selected Business Group: ${{ parameters.businessGroup }}"
        echo "Selected Environment: ${{ parameters.environment }}"